version: "3.8"

services: 
  server:
    image: kevin9foong/orbital-server:dev
    build: 
      context: .
      target: dev
    container_name: orbital-server
    ports:
      - 3000:3000
    volumes:
      - ./:/app

